# Generated by Django 4.1.4 on 2022-12-26 19:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bitcoin_emissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pool",
            name="locations",
            field=models.ManyToManyField(
                through="bitcoin_emissions.PoolLocation",
                to="bitcoin_emissions.location",
            ),
        ),
        migrations.AlterField(
            model_name="uuidmodel",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
