# Generated by Django 4.1.4 on 2022-12-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bitcoin_emissions", "0002_pool_locations_alter_uuidmodel_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="poollocation",
            name="emission_factor",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="poollocation",
            name="information_source",
            field=models.CharField(default="N/A", max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="CO2EmissionFactor",
        ),
    ]
