# Generated by Django 4.1.4 on 2022-12-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bitcoin_emissions", "0003_poollocation_emission_factor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poollocation",
            name="emission_factor",
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
    ]
