# Generated by Django 4.1.4 on 2023-01-07 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bitcoin_emissions", "0004_alter_poollocation_emission_factor"),
    ]

    operations = [
        migrations.AddField(
            model_name="poolelectricityconsumptionandco2eemissionhistory",
            name="location_of_servers",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="bitcoin_emissions.location",
            ),
            preserve_default=False,
        ),
    ]
