# Generated by Django 4.1.4 on 2023-01-18 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "bitcoin_emissions",
            "0005_poolelectricityconsumptionandco2eemissionhistory_location_of_servers",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AverageEfficiency",
            fields=[
                (
                    "uuidmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="bitcoin_emissions.uuidmodel",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "average_efficiency_j_gh",
                    models.DecimalField(decimal_places=12, max_digits=100),
                ),
            ],
            bases=("bitcoin_emissions.uuidmodel",),
        ),
        migrations.CreateModel(
            name="NetworkHashRate",
            fields=[
                (
                    "uuidmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="bitcoin_emissions.uuidmodel",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "network_hash_rate_eh_s",
                    models.DecimalField(decimal_places=12, max_digits=100),
                ),
            ],
            bases=("bitcoin_emissions.uuidmodel",),
        ),
    ]
