# Generated by Django 4.1.4 on 2023-01-20 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bitcoin_emissions", "0006_averageefficiency_networkhashrate"),
    ]

    operations = [
        migrations.CreateModel(
            name="HashRatePerPoolServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash_rate", models.DecimalField(decimal_places=12, max_digits=100)),
                (
                    "blockchain_pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bitcoin_emissions.pool",
                    ),
                ),
                (
                    "blockchain_pool_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bitcoin_emissions.location",
                    ),
                ),
            ],
        ),
    ]
