# Generated by Django 4.1.4 on 2023-01-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bitcoin_emissions", "0007_hashrateperpoolserver"),
    ]

    operations = [
        migrations.AddField(
            model_name="hashrateperpoolserver",
            name="date",
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
