# Generated by Django 4.1.4 on 2024-03-29 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_emissions', '0008_hashrateperpoolserver_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CO2ElectricityHistoryPerServer',
            fields=[
                ('uuidmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bitcoin_emissions.uuidmodel')),
                ('date', models.DateField()),
                ('electricity_usage', models.DecimalField(decimal_places=6, max_digits=24)),
                ('co2e_emissions', models.DecimalField(decimal_places=6, max_digits=24)),
                ('server_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitcoin_emissions.poollocation')),
            ],
            bases=('bitcoin_emissions.uuidmodel',),
        ),
    ]
