# Generated by Django 4.1.4 on 2024-06-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_emissions', '0009_co2electricityhistoryperserver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='averageefficiency',
            options={'verbose_name_plural': 'Average gear efficiency'},
        ),
        migrations.AlterModelOptions(
            name='bitcoindifficulty',
            options={'verbose_name_plural': 'Bitcoin mining difficulty'},
        ),
        migrations.AlterModelOptions(
            name='co2electricityhistoryperserver',
            options={'verbose_name_plural': 'Emissions history per pool'},
        ),
        migrations.AlterModelOptions(
            name='networkhashrate',
            options={'verbose_name_plural': 'Network hash rate'},
        ),
        migrations.AlterModelOptions(
            name='poolelectricityconsumptionandco2eemissionhistory',
            options={'verbose_name_plural': 'Emissions history per location'},
        ),
        migrations.AlterModelOptions(
            name='poollocation',
            options={'verbose_name_plural': 'Servers (Location + Pool combinations)'},
        ),
        migrations.AddIndex(
            model_name='co2electricityhistoryperserver',
            index=models.Index(fields=['date'], name='bitcoin_emi_date_23d94f_idx'),
        ),
        migrations.AddIndex(
            model_name='hashrateperpoolserver',
            index=models.Index(fields=['date', 'blockchain_pool_location'], name='bitcoin_emi_date_7764aa_idx'),
        ),
        migrations.AddIndex(
            model_name='poolelectricityconsumptionandco2eemissionhistory',
            index=models.Index(fields=['date'], name='bitcoin_emi_date_68869f_idx'),
        ),
        migrations.AddIndex(
            model_name='poollocation',
            index=models.Index(fields=['blockchain_pool_location'], name='bitcoin_emi_blockch_f45b3f_idx'),
        ),
    ]
